.\"@mindmaze_header@
.TH MMLOG_FATAL 3 2012 "MINDMAZE" "mmlib library manual"
.SH NAME
mmlog_fatal, mmlog_error, mmlog_warn, mmlog_info, mmlog_debug - Add a formatted message to the log file
.SH SYNOPSIS
.LP
.B #include <mmlog.h>
.sp
.BI "void mmlog_fatal(msg, ...);"
.br
.BI "void mmlog_error(msg, ...);"
.br
.BI "void mmlog_warn(msg, ...);"
.br
.BI "void mmlog_info(msg, ...);"
.br
.BI "void mmlog_debug(msg, ...);"
.br
.sp
Link with
.I -lmmlib
.SH DESCRIPTION
.LP
Those macros writes a log entry (using \fBmmlog_log\fP(3)) using the level
specified by the macro name. If the preprocessor definition
\fIMMLOG_MAXLEVEL\fP is smaller than the corresponding level of the macro,
this macros is simply not exanded in the code.
.LP
The module name in the location string is defined by
\fIMMLOG_MODULE_NAME\fP. If unset when including \fBmmlog.h\fP, this
definition is intialized to the value of \fIPACKAGE_NAME\fP. If
\fIMMLOG_VERBOSE_LOCATION\fP is defined, the filename and line number are
prepended to the location string.
.SH "RETURN VALUE"
.LP
None.
.SH THREAD SAFETY
.LP
\fBmmlog_log\fP() is thread-safe.
.SH EXAMPLE
.LP

